// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEgj8sDprSmOFidnjbQljFPHBDqwsTfoo',
    appId: '1:921669094598:web:ec4ecdb72bbfd60fde9bc7',
    messagingSenderId: '921669094598',
    projectId: 'fitness-app-9f99c',
    authDomain: 'fitness-app-9f99c.firebaseapp.com',
    storageBucket: 'fitness-app-9f99c.appspot.com',
    measurementId: 'G-FZPW9EX65W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyqHkNVdxSqg9OxPBW7iSyEOubBqKrvWs',
    appId: '1:921669094598:android:c3939cbf404a65f4de9bc7',
    messagingSenderId: '921669094598',
    projectId: 'fitness-app-9f99c',
    storageBucket: 'fitness-app-9f99c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcym1c95nt4BYcyljMtodquDoUM0udyS8',
    appId: '1:921669094598:ios:28e2e4a50c2a507bde9bc7',
    messagingSenderId: '921669094598',
    projectId: 'fitness-app-9f99c',
    storageBucket: 'fitness-app-9f99c.appspot.com',
    iosClientId: '921669094598-g7c5j5b2olpol9bh6qf4ufa49l0h6orb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcym1c95nt4BYcyljMtodquDoUM0udyS8',
    appId: '1:921669094598:ios:28e2e4a50c2a507bde9bc7',
    messagingSenderId: '921669094598',
    projectId: 'fitness-app-9f99c',
    storageBucket: 'fitness-app-9f99c.appspot.com',
    iosClientId: '921669094598-g7c5j5b2olpol9bh6qf4ufa49l0h6orb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );
}
